- hosts: all

  roles:
    - geerlingguy.pip

  tasks:

    - name: Start a container
      community.docker.docker_container:
        name: app
        image: redmine
        ports:
          - "80:3000"
        env:
          REDMINE_DB_POSTGRES: "{{DB_POSTGRES}}"
          REDMINE_DB_DATABASE: "{{DB_DATABASE}}"
          REDMINE_DB_USERNAME: "{{DB_USERNAME}}"
          REDMINE_DB_PASSWORD: "{{DB_PASSWORD}}"
          REDMINE_DB_PORT: "{{DB_PORT}}"

    - name: Run datadog
      include_role:
        name: datadog.datadog
        apply:
          become: yes
